# [Required]
# Basic component information
repo: test-ioc
organization: ad-build-test
url: https://github.com/ad-build-test/test-ioc
description: IOC for testing software factory

# [Required]
# Continous integration
approvalRule: all
testingCriteria: all
issueTracker: github
jiraProjectKey: n/a

# [Required]
# Type of deployment
# Types: [ioc, hla, tools, matlab, pydm, container]
deploymentType: ioc

# [Optional] 
# Build method for building the component
# Can be a simple command like 'make'
build: make

# [Optional]
# Environments this app runs on
environments:
   - ROCKY9
   - RHEL7

# [Optional]
# Directories and files needed to run application
runtimeDependencies:
   - bin
   - iocBoot
   - db
   - dbd
   - mock_runtime_dependency.txt
